name: Testing the GitHub Pages publication

on:
  pull_request:
    branches:
      - gh-pages

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          with:
            token: ${{secrets.GITHUB_TOKEN}}

      ## 1
      - name: remove files
        run: |
          rm -r -f -v  Gemfile.lock

      - uses: helaili/jekyll-action@v2
         with:
            target_branch: preview/${github.head_ref}
            # target_path: v1.0
            keep_history: true #2
            token: ${{ secrets.GITHUB_TOKEN }}
