name: Testing the GitHub Pages publication

on:
  pull_request:
    branches:
      - gh-pages

jobs:
  jekyll:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: remove files
        ## Ruby バージョンの要件が競合するのを防ぐ
        run: |
          rm -r -f -v  Gemfile.lock

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
          bundler-cache: true

      - run: |
          bundle exec jekyll build

      - uses: actions/upload-artifact@v2
        with:
          name: _site
          path: _site

  screenshot:
    runs-on: ubuntu-latest
    needs: jekyll
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: _site
          path: _site

      - name: Change language Japanese
        run: |
          sudo apt-get update
          sudo apt-get install language-pack-ja
          sudo update-locale LANG=ja_JP.UTF-8
          sudo apt-get install fonts-ipafont-gothic fonts-ipafont-mincho

      - name: move file
        continue-on-error: true
        ## setup-nodeの仕様上ルートファイルで実行されるため
        run: |
          mv  -v -f .github/GH-preview/* .
          mv  -v -f .github/GH-preview/.* .

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: |
            yarn.lock
            .yarn
            node_modules

      - name: Playwright CLI Setup
        ## https://github.com/microsoft/playwright-github-action
        run: |
          npx playwright install-deps

      - name: Install deps
        run: |
          yarn set version berry
          yarn
      - name: Build
        run: |
          yarn run build
      - uses: actions/upload-artifact@v2
        with:
          name: result.jpg
          path: result.jpg

##      - name: Create comments
##        run: |
##          cat << EOF > comments
##          ## サイトプレビュー
##          EOF
##          echo ”https://github.com/Numa-Lab/www.numalab.net/runs/${github.run_id}” >> comments
##
##      - name: Post multi-line comments
##        env:
##          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
##          URL: ${{ github.event.pull_request.html_url }}
##        run:
##          gh pr comment -F ./comments "${URL}"
