name: Testing the GitHub Pages publication

on:
  pull_request:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/jekyll-build-pages@v1
        with:
          source: .
          destination: ./_site
      - uses: actions/upload-artifact@v2
        with:
          name: _site
          path: _site
          if-no-files-found: warn

  screenshot:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: _site
          path: _site

      - name: Change language Japanese
        run: |
          sudo apt-get update
          sudo apt-get install language-pack-ja
          sudo update-locale LANG=ja_JP.UTF-8
      - name: move file
        continue-on-error: true
        ## setup-nodeの仕様上ルートファイルで実行されるため
        ## パスの関係上、ルートで実行するため
        run: |
          sudo mv -v -f .github/GH-preview .
          sudo mv -v -f _site .
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache-dependency-path: |
            .yarn
            node_modules
      - name: Playwright CLI Setup
        ## https://github.com/microsoft/playwright-github-action
        run: |
          npx playwright install-deps chromium
      - name: Install deps
        run: |
          yarn set version berry
          YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install
      - name: Build
        run: |
          yarn run build
      - uses: actions/upload-artifact@v2
        with:
          name: result.jpg
          path: result.jpg

##      - name: Create comments
##        run: |
##          cat << EOF > comments
##          ## サイトプレビュー
##          EOF
##          echo ”https://github.com/Numa-Lab/www.numalab.net/runs/${github.run_id}” >> comments
##
##      - name: Post multi-line comments
##        env:
##          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
##          URL: ${{ github.event.pull_request.html_url }}
##        run:
##          gh pr comment -F ./comments "${URL}"